# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  #config.vm.network "private_network", type: "dhcp"
  #config.vm.provision "shell", inline: "/vagrant/init.sh"

  config.vm.define "master" do |master|
  master.vm.box = "ctos_6.6_x64"
  master.vm.host_name = "tts-master"
  master.vm.network "private_network", ip: "10.10.0.5"
  end

  config.vm.define "slave1" do |slave1|
  slave1.vm.box = "ctos_6.6_x64"
  slave1.vm.host_name = "tts-slave1"
  slave1.vm.network "private_network", ip: "10.10.0.6"
  end

  config.vm.define "slave2" do |slave2|
  slave2.vm.box = "ctos_6.6_x64"
  slave2.vm.host_name = "tts-slave2"
  slave2.vm.network "private_network", ip: "10.10.0.7"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.cpus = "1"
  end
end

